FROM ubuntu:20.04

# Application should not ask questions during configuration
ENV DEBIAN_FRONTEND=noninteractive

# Update packages available
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    python3-pyqt5 \
    python3-zmq \
    libcanberra-gtk-module \
    git make gcc g++ libssl-dev

# cFS dependencies
RUN apt-get install -y cmake build-essential gcc-multilib g++-multilib

# Generic dependencies needed
RUN apt-get install -y git

# Get copy of cFS ground system
RUN git clone --recursive https://github.com/samiphegde/ESSCT.git
WORKDIR /ESSCT/cFS/tools/cFS-GroundSystem/Subsystems/cmdUtil/
#RUN make

# Create OffsetData with default values
RUN echo -ne '\x04\x00\x00' > /tmp/OffsetData

CMD /bin/bash -c "\
    echo '[INFO] Starting Ground System...' && \
    python3 /ESSCT/cFS/tools/cFS-GroundSystem/GroundSystem.py & \
    echo '[INFO] Waiting for Ground System to initialize...' && \
    sleep 5 && \
    echo '[INFO] Running Auto Commander...' && \
    python3 /ESSCT/cFS/tools/cFS-GroundSystem/Subsystems/cmdGui/auto_commander.py"
#   python3 /ESSCT/cFS/tools/cFS-GroundSystem/Subsystems/cmdGui/user_inp_auto_commander.py

#CMD ["python3", "/cFS-GroundSystem/GroundSystem.py"]
